name: Docker Image CI

on:
  push:
    branches: [ "stable", "dev" ]
  pull_request:
    branches: [ "stable", "dev" ]

jobs:

  build:

    runs-on: hosting3

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag ethtps-frontend:$(date +%s)
      
