name: Prettier test

on:
  push:
    branches: [ "main", "dev", "testing" ]
  pull_request:
    branches: [ "main", "dev","testing"  ]

jobs:
  build:

    runs-on: Windows

    strategy:
      matrix:
        node-version: [20.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm install --global prettier
    - run: npm run prettier:fix

    - name: Install Yarn
      run: npm install -g yarn

    - name: Install global dependencies
      run: yarn global add typescript

    - name: Install dependencies and build
      run: npm run relink-deps ; npx yarn install --force ; npm run build
